 tags:
     - v**

permissions:
  contents: write

jobs: 

  build_packages_Linux:
@@ -29,7 +32,7 @@ jobs:
    - name: Make a release
      uses: ncipollo/release-action@v1.10.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "build/*.deb,build/*.tar.gz,build/*.zip"


        replacesArtifacts: false
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        allowUpdates: true
